#define INTERFACE 0

#define FOL_PARSE_TOKEN_MINUS                          17
#define FOL_PARSE_TOKEN_NUMBER                         16
#define FOL_PARSE_TOKEN_STRING                         15
#define FOL_PARSE_TOKEN_DOT                            14
#define FOL_PARSE_TOKEN_WS                             13
#define FOL_PARSE_TOKEN_NEGATION                       12
#define FOL_PARSE_TOKEN_REVERSE_IMPLICATION            11
#define FOL_PARSE_TOKEN_IMPLICATION                    10
#define FOL_PARSE_TOKEN_RBRACKET                        9
#define FOL_PARSE_TOKEN_LBRACKET                        8
#define FOL_PARSE_TOKEN_DISJUNCTION                     7
#define FOL_PARSE_TOKEN_CONJUNCTION                     6
#define FOL_PARSE_TOKEN_NEWLINE                         5
#define FOL_PARSE_TOKEN_RPAREN                          4
#define FOL_PARSE_TOKEN_LPAREN                          3
#define FOL_PARSE_TOKEN_COMMA                           2
#define FOL_PARSE_TOKEN_EQUAL                           1


#define ASP_PARSE_TOKEN_MINUS                          17
#define ASP_PARSE_TOKEN_NUMBER                         16
#define ASP_PARSE_TOKEN_STRING                         15
#define ASP_PARSE_TOKEN_DOT                            14
#define ASP_PARSE_TOKEN_WS                             13
#define ASP_PARSE_TOKEN_NEGATION                       12
#define ASP_PARSE_TOKEN_REVERSE_IMPLICATION            11
#define ASP_PARSE_TOKEN_IMPLICATION                    10
#define ASP_PARSE_TOKEN_RBRACKET                        9
#define ASP_PARSE_TOKEN_LBRACKET                        8
#define ASP_PARSE_TOKEN_DISJUNCTION                     7
#define ASP_PARSE_TOKEN_CONJUNCTION                     6
#define ASP_PARSE_TOKEN_NEWLINE                         5
#define ASP_PARSE_TOKEN_RPAREN                          4
#define ASP_PARSE_TOKEN_LPAREN                          3
#define ASP_PARSE_TOKEN_COMMA                           2
#define ASP_PARSE_TOKEN_EQUAL                           1


#define MVSM_PARSE_TOKEN_REVERSE_IMPLICATION             1
#define MVSM_PARSE_TOKEN_EQUAL                           2
#define MVSM_PARSE_TOKEN_COMMA                           3
#define MVSM_PARSE_TOKEN_LPAREN                          4
#define MVSM_PARSE_TOKEN_RPAREN                          5
#define MVSM_PARSE_TOKEN_NEWLINE                         6
#define MVSM_PARSE_TOKEN_CONJUNCTION                     7
#define MVSM_PARSE_TOKEN_DISJUNCTION                     8
#define MVSM_PARSE_TOKEN_LBRACKET                        9
#define MVSM_PARSE_TOKEN_RBRACKET                       10
#define MVSM_PARSE_TOKEN_IMPLICATION                    11
#define MVSM_PARSE_TOKEN_SORTS                          12
#define MVSM_PARSE_TOKEN_NEGATION                       13
#define MVSM_PARSE_TOKEN_WS                             14
#define MVSM_PARSE_TOKEN_SEMI_COLON                     15
#define MVSM_PARSE_TOKEN_DOT                            16
#define MVSM_PARSE_TOKEN_OBJECTS                        17
#define MVSM_PARSE_TOKEN_COLON                          18
#define MVSM_PARSE_TOKEN_CONSTANTS                      19
#define MVSM_PARSE_TOKEN_COUNT                          20
#define MVSM_PARSE_TOKEN_SUM                            21
#define MVSM_PARSE_TOKEN_STRING                         22
#define MVSM_PARSE_TOKEN_NUMBER                         23