/* Generated by re2c 0.16 on Tue Jul 26 03:01:44 2016 */
#line 1 "src/src/MVSMLexer.re"
#include "MVSMLexer.h"
#include "exceptions/syntax_exception.h"

int MVSMLexer::Tokenize(const char * YYCURSOR, int len , lexeme_t* lexeme)
{

 	if (lexeme->current >= (YYCURSOR + len)) {
        return 0;
    }
    lexeme->start = lexeme->current;

    const char * YYMARKER;
	#define YYCURSOR lexeme->current

	
#line 19 "<stdout>"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy6;
	case '\n':	goto yy8;
	case '!':	goto yy10;
	case '(':	goto yy12;
	case ')':	goto yy14;
	case ',':	goto yy16;
	case '-':	goto yy18;
	case '.':	goto yy20;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	case ':':	goto yy25;
	case ';':	goto yy27;
	case '<':	goto yy29;
	case '=':	goto yy30;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy32;
	case 'N':	goto yy35;
	case '^':	goto yy36;
	case 'n':	goto yy38;
	case '{':	goto yy39;
	case '}':	goto yy41;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 20 "src/src/MVSMLexer.re"
	{ return 0; }
#line 113 "<stdout>"
yy4:
	++YYCURSOR;
yy5:
#line 54 "src/src/MVSMLexer.re"
	{
									std::string str(--lexeme->current,0,1);
									throw syntax_exception("Syntax Error - Unexpected "+ str +"\n");
								}
#line 122 "<stdout>"
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy43;
	case 'v':	goto yy46;
	default:	goto yy7;
	}
yy7:
#line 52 "src/src/MVSMLexer.re"
	{ return -1; }
#line 137 "<stdout>"
yy8:
	++YYCURSOR;
#line 53 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_NEWLINE; }
#line 142 "<stdout>"
yy10:
	++YYCURSOR;
#line 42 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_NEGATION;}
#line 147 "<stdout>"
yy12:
	++YYCURSOR;
#line 29 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_LBRACKET; }
#line 152 "<stdout>"
yy14:
	++YYCURSOR;
#line 30 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_RBRACKET; }
#line 157 "<stdout>"
yy16:
	++YYCURSOR;
#line 31 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_COMMA; }
#line 162 "<stdout>"
yy18:
	++YYCURSOR;
#line 40 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_MINUS;}
#line 167 "<stdout>"
yy20:
	++YYCURSOR;
#line 19 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_DOT; }
#line 172 "<stdout>"
yy22:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	default:	goto yy24;
	}
yy24:
#line 21 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_NUMBER; }
#line 193 "<stdout>"
yy25:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '-':	goto yy47;
	default:	goto yy26;
	}
yy26:
#line 50 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_COLON; }
#line 204 "<stdout>"
yy27:
	++YYCURSOR;
#line 48 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_SEMI_COLON;}
#line 209 "<stdout>"
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy49;
	default:	goto yy5;
	}
yy30:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '>':	goto yy51;
	default:	goto yy31;
	}
yy31:
#line 28 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_EQUAL; }
#line 225 "<stdout>"
yy32:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy33:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy32;
	default:	goto yy34;
	}
yy34:
#line 23 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_STRING; }
#line 299 "<stdout>"
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy53;
	default:	goto yy33;
	}
yy36:
	++YYCURSOR;
#line 32 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_CONJUNCTION; }
#line 310 "<stdout>"
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy54;
	default:	goto yy33;
	}
yy39:
	++YYCURSOR;
#line 27 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_LPAREN; }
#line 321 "<stdout>"
yy41:
	++YYCURSOR;
#line 26 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_RPAREN; }
#line 326 "<stdout>"
yy43:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy43;
	case 'v':	goto yy46;
	default:	goto yy45;
	}
yy45:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy7;
	} else {
		goto yy26;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy55;
	default:	goto yy45;
	}
yy47:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy47;
	case 'c':	goto yy58;
	case 'o':	goto yy59;
	case 's':	goto yy60;
	default:	goto yy45;
	}
yy49:
	++YYCURSOR;
#line 25 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_REVERSE_IMPLICATION; }
#line 373 "<stdout>"
yy51:
	++YYCURSOR;
#line 24 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_IMPLICATION; }
#line 378 "<stdout>"
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy61;
	default:	goto yy33;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy61;
	default:	goto yy33;
	}
yy55:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy55;
	default:	goto yy57;
	}
yy57:
#line 33 "src/src/MVSMLexer.re"
	{
									while(*(lexeme->start) != 'v') lexeme->start++;
									while(*(lexeme->current) != 'v') lexeme->current--;
									lexeme->current++; 
									return MVSM_PARSE_TOKEN_DISJUNCTION;
								}
#line 410 "<stdout>"
yy58:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy63;
	default:	goto yy45;
	}
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy64;
	default:	goto yy45;
	}
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy65;
	default:	goto yy45;
	}
yy61:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy32;
	default:	goto yy62;
	}
yy62:
#line 22 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_NEGATION;}
#line 499 "<stdout>"
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy66;
	default:	goto yy45;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'j':	goto yy67;
	default:	goto yy45;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy68;
	default:	goto yy45;
	}
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy69;
	default:	goto yy45;
	}
yy67:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy70;
	default:	goto yy45;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy71;
	default:	goto yy45;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy72;
	default:	goto yy45;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy73;
	default:	goto yy45;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy74;
	default:	goto yy45;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy76;
	default:	goto yy45;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy77;
	default:	goto yy45;
	}
yy74:
	++YYCURSOR;
#line 44 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_SORTS;}
#line 570 "<stdout>"
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy78;
	default:	goto yy45;
	}
yy77:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy79;
	default:	goto yy45;
	}
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy81;
	default:	goto yy45;
	}
yy79:
	++YYCURSOR;
#line 45 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_OBJECTS;}
#line 593 "<stdout>"
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy82;
	default:	goto yy45;
	}
yy82:
	++YYCURSOR;
#line 46 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_CONSTANTS;}
#line 604 "<stdout>"
}
#line 59 "src/src/MVSMLexer.re"


}