#define MVSM_PARSE_TOKEN_REVERSE_IMPLICATION              1
#define MVSM_PARSE_TOKEN_EQUAL                            2
#define MVSM_PARSE_TOKEN_COMMA                            3
#define MVSM_PARSE_TOKEN_LPAREN                           4
#define MVSM_PARSE_TOKEN_RPAREN                           5
#define MVSM_PARSE_TOKEN_NEWLINE                          6
#define MVSM_PARSE_TOKEN_CONJUNCTION                      7
#define MVSM_PARSE_TOKEN_DISJUNCTION                      8
#define MVSM_PARSE_TOKEN_LBRACKET                         9
#define MVSM_PARSE_TOKEN_RBRACKET                        10
#define MVSM_PARSE_TOKEN_IMPLICATION                     11
#define MVSM_PARSE_TOKEN_SORTS                           12
#define MVSM_PARSE_TOKEN_NEGATION                        13
#define MVSM_PARSE_TOKEN_WS                              14
#define MVSM_PARSE_TOKEN_SEMI_COLON                      15
#define MVSM_PARSE_TOKEN_DOT                             16
#define MVSM_PARSE_TOKEN_OBJECTS                         17
#define MVSM_PARSE_TOKEN_COLON                           18
#define MVSM_PARSE_TOKEN_CONSTANTS                       19
#define MVSM_PARSE_TOKEN_STRING                          20
#define MVSM_PARSE_TOKEN_NUMBER                          21
#define MVSM_PARSE_TOKEN_MINUS                           22
