/* Generated by re2c 0.16 on Mon Oct 17 21:05:22 2016 */
#line 1 "src/src/MVSMLexer.re"
#include "MVSMLexer.h"
#include "exceptions/syntax_exception.h"

int MVSMLexer::Tokenize(const char * YYCURSOR, int len , lexeme_t* lexeme)
{

 	if (lexeme->current >= (YYCURSOR + len)) {
        return 0;
    }
    lexeme->start = lexeme->current;

    const char * YYMARKER;
	#define YYCURSOR lexeme->current

	
#line 19 "<stdout>"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;
	if ((YYLIMIT - YYCURSOR) < 6) YYFILL(6);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy6;
	case '\n':	goto yy8;
	case '!':	goto yy10;
	case '#':	goto yy12;
	case '(':	goto yy13;
	case ')':	goto yy15;
	case ',':	goto yy17;
	case '-':	goto yy19;
	case '.':	goto yy20;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	case ':':	goto yy25;
	case ';':	goto yy27;
	case '<':	goto yy29;
	case '=':	goto yy30;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy32;
	case 'N':	goto yy35;
	case '^':	goto yy36;
	case 'n':	goto yy38;
	case '{':	goto yy39;
	case '}':	goto yy41;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 20 "src/src/MVSMLexer.re"
	{ return 0; }
#line 114 "<stdout>"
yy4:
	++YYCURSOR;
yy5:
#line 56 "src/src/MVSMLexer.re"
	{
									std::string str(--lexeme->current,0,1);
									throw syntax_exception("Syntax Error - Unexpected "+ str +"\n");
								}
#line 123 "<stdout>"
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy43;
	case 'v':	goto yy46;
	default:	goto yy7;
	}
yy7:
#line 54 "src/src/MVSMLexer.re"
	{ return -1; }
#line 138 "<stdout>"
yy8:
	++YYCURSOR;
#line 55 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_NEWLINE; }
#line 143 "<stdout>"
yy10:
	++YYCURSOR;
#line 44 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_NEGATION;}
#line 148 "<stdout>"
yy12:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'c':	goto yy47;
	default:	goto yy5;
	}
yy13:
	++YYCURSOR;
#line 30 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_LBRACKET; }
#line 160 "<stdout>"
yy15:
	++YYCURSOR;
#line 31 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_RBRACKET; }
#line 165 "<stdout>"
yy17:
	++YYCURSOR;
#line 32 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_COMMA; }
#line 170 "<stdout>"
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	default:	goto yy5;
	}
yy20:
	++YYCURSOR;
#line 19 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_DOT; }
#line 190 "<stdout>"
yy22:
	yyaccept = 2;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy48;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy22;
	default:	goto yy24;
	}
yy24:
#line 22 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_NUMBER; }
#line 213 "<stdout>"
yy25:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '-':	goto yy49;
	default:	goto yy26;
	}
yy26:
#line 52 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_COLON; }
#line 224 "<stdout>"
yy27:
	++YYCURSOR;
#line 50 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_SEMI_COLON;}
#line 229 "<stdout>"
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
	case '=':	goto yy51;
	default:	goto yy5;
	}
yy30:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '>':	goto yy53;
	default:	goto yy31;
	}
yy31:
#line 29 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_EQUAL; }
#line 245 "<stdout>"
yy32:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy33:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy32;
	default:	goto yy34;
	}
yy34:
#line 24 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_STRING; }
#line 319 "<stdout>"
yy35:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy55;
	default:	goto yy33;
	}
yy36:
	++YYCURSOR;
#line 33 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_CONJUNCTION; }
#line 330 "<stdout>"
yy38:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy56;
	default:	goto yy33;
	}
yy39:
	++YYCURSOR;
#line 28 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_LPAREN; }
#line 341 "<stdout>"
yy41:
	++YYCURSOR;
#line 27 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_RPAREN; }
#line 346 "<stdout>"
yy43:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy43;
	case 'v':	goto yy46;
	default:	goto yy45;
	}
yy45:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy7;
	case 1: 	goto yy5;
	case 2: 	goto yy24;
	default:	goto yy26;
	}
yy46:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy57;
	default:	goto yy45;
	}
yy47:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy60;
	default:	goto yy45;
	}
yy48:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy61;
	default:	goto yy45;
	}
yy49:
	++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 9) YYFILL(9);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy49;
	case 'c':	goto yy63;
	case 'o':	goto yy64;
	case 's':	goto yy65;
	default:	goto yy45;
	}
yy51:
	++YYCURSOR;
#line 26 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_REVERSE_IMPLICATION; }
#line 415 "<stdout>"
yy53:
	++YYCURSOR;
#line 25 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_IMPLICATION; }
#line 420 "<stdout>"
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy66;
	default:	goto yy33;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy66;
	default:	goto yy33;
	}
yy57:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy57;
	default:	goto yy59;
	}
yy59:
#line 35 "src/src/MVSMLexer.re"
	{
									while(*(lexeme->start) != 'v') lexeme->start++;
									while(*(lexeme->current) != 'v') lexeme->current--;
									lexeme->current++; 
									return MVSM_PARSE_TOKEN_DISJUNCTION;
								}
#line 452 "<stdout>"
yy60:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy68;
	default:	goto yy45;
	}
yy61:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy61;
	default:	goto yy24;
	}
yy63:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy69;
	default:	goto yy45;
	}
yy64:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy70;
	default:	goto yy45;
	}
yy65:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy71;
	default:	goto yy45;
	}
yy66:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy32;
	default:	goto yy67;
	}
yy67:
#line 23 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_NEGATION;}
#line 564 "<stdout>"
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy72;
	default:	goto yy45;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy73;
	default:	goto yy45;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'j':	goto yy74;
	default:	goto yy45;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy75;
	default:	goto yy45;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy76;
	default:	goto yy45;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy78;
	default:	goto yy45;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy79;
	default:	goto yy45;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy80;
	default:	goto yy45;
	}
yy76:
	++YYCURSOR;
#line 34 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_COUNT;}
#line 617 "<stdout>"
yy78:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy81;
	default:	goto yy45;
	}
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy82;
	default:	goto yy45;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy83;
	default:	goto yy45;
	}
yy81:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy85;
	default:	goto yy45;
	}
yy82:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy86;
	default:	goto yy45;
	}
yy83:
	++YYCURSOR;
#line 46 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_SORTS;}
#line 652 "<stdout>"
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy87;
	default:	goto yy45;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy88;
	default:	goto yy45;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy90;
	default:	goto yy45;
	}
yy88:
	++YYCURSOR;
#line 47 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_OBJECTS;}
#line 675 "<stdout>"
yy90:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy91;
	default:	goto yy45;
	}
yy91:
	++YYCURSOR;
#line 48 "src/src/MVSMLexer.re"
	{ return MVSM_PARSE_TOKEN_CONSTANTS;}
#line 686 "<stdout>"
}
#line 61 "src/src/MVSMLexer.re"


}