#define PARSE_TOKEN_EQUAL                            1
#define PARSE_TOKEN_COMMA                            2
#define PARSE_TOKEN_LPAREN                           3
#define PARSE_TOKEN_RPAREN                           4
#define PARSE_TOKEN_NEWLINE                          5
#define PARSE_TOKEN_CONJUNCTION                      6
#define PARSE_TOKEN_DISJUNCTION                      7
#define PARSE_TOKEN_LBRACKET                         8
#define PARSE_TOKEN_RBRACKET                         9
#define PARSE_TOKEN_IMPLICATION                     10
#define PARSE_TOKEN_NEGATION                        11
#define PARSE_TOKEN_WS                              12
#define PARSE_TOKEN_DOT                             13
#define PARSE_TOKEN_STRING                          14
#define PARSE_TOKEN_NUMBER                          15
#define PARSE_TOKEN_MINUS                           16
